// Generated by  : ImageConverter 565 v2.3
// Generated from: clear.png
// Time generated: 14/09/2019 16:20:12
// Dimensions    : 48x48 pixels
// Size          : 4,608 Bytes

// Icons from
// https://www.deviantart.com/umutavci/art/weather-icon-set-165476034

#include <avr/pgmspace.h>

#include "icon_01d.h"
#include "icon_02d.h"
#include "icon_03d.h"
#include "icon_09d.h"
#include "icon_10d.h"
#include "icon_11d.h"
#include "icon_13d.h"
#include "icon_50d.h"
#include "icon_01n.h"
#include "icon_02n.h"
#include "icon_09n.h"
#include "icon_11n.h"
#include "icon_13n.h"