#include <avr/pgmspace.h>

const char index_html[] PROGMEM =
{

"<!doctype html><html lang=\"en\"> <head> <meta charset=\"utf-8\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"> <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\"> <link rel=\"stylesheet\" href=\"css/station.css\"> <title>OctoPrint Monitor | Dashboard</title> </head> <body> %NAVBAR% <div class=\"container-fluid\" style=\"margin-top:80px\"> <h3 id=\"dashboardTitle\">Dashboard - not connected</h3> <table class=\"table\" style=\"background-color: white\"> <thead class=\"thead-light\"> <tr> <th>Print Monitor Info</th> </tr></thead> <tbody> <tr> <td> <ul id=\"monitorInfoList\" class=\"list-group\"> <li class=\"list-group-item\">Waiting...</li></ul> </td></tr></tbody> </table> <table class=\"table\" style=\"background-color: white\"> <thead class=\"thead-light\"> <tr> <th>Internet current weather</th> </tr></thead> <tbody> <tr> <td> <ul id=\"internetWeatherList\" class=\"list-group\"> <li class=\"list-group-item\">Waiting...</li></ul> </td></tr></tbody> </table> </div><script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script> <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script> <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script> <script src=\"js/station.js\"></script> </body></html>"

};

const char station_js[] PROGMEM =
{

"var websocket;\n"
"\n"
"function init()\n"
"{   \n"
"    openWebSocket();\n"
"}\n"
"\n"
"function updateInternetCurrent(messageData)\n"
"{\n"
"    var current = messageData.currentReadings;\n"
"    var currentValue;\n"
"    var observedTime;\n"
"   \n"
"    $(\"#internetWeatherList\").empty();\n"
"\n"
"    if(current.metric)\n"
"    {\n"
"        currentValue = current.temp.toFixed(1) + \"C - \" + current.description;\n"
"    }\n"
"    else\n"
"    {\n"
"        currentValue = current.temp.toFixed(1) + \"F - \" + current.description;\n"
"    }\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"    \n"
"    currentValue = \"Humidity: \" + current.humidity + \"%\";\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"    \n"
"    currentValue = \"Wind speed: \" + current.windSpeed + \"m/s from \" + current.windDirection + \"&#176\";\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"\n"
"    observedTime = new Date(current.time * 1000);\n"
"    currentValue = \"Observed at: \" + observedTime.toLocaleTimeString(\"en-GB\") + \" on \" + observedTime.toLocaleDateString(\"en-GB\");\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"}\n"
"\n"
"function updateMonitorInfo(messageData)\n"
"{\n"
"    $(\"#monitorInfoList\").empty();\n"
"\n"
"    if(messageData.enabled)\n"
"    {\n"
"        if(messageData.validPrintData)\n"
"        {\n"
"            $(\"#monitorInfoList\").append('<li class=\"list-group-item\">' + messageData.printerName + ' - state: ' + messageData.printState + '</li>');    \n"
"        }\n"
"        else\n"
"        {\n"
"            $(\"#monitorInfoList\").append('<li class=\"list-group-item\">' + messageData.printerName + ' - no valid data received.' + '</li>');    \n"
"        }\n"
"    }\n"
"    else\n"
"    {\n"
"        $(\"#monitorInfoList\").append('<li class=\"list-group-item\">' + messageData.printerName + ' - not enabled.' + '</li>');\n"
"    }\n"
"}\n"
"\n"
"function openWebSocket() \n"
"{\n"
"    websocket = new WebSocket('ws://' + document.location.host + '/ws');\n"
"    websocket.onopen = function(evt) { onOpen(evt) };\n"
"    websocket.onclose = function(evt) { onClose(evt) };\n"
"    websocket.onmessage = function(evt) { onMessage(evt) };\n"
"    websocket.onerror = function(evt) { onError(evt) };\n"
"}\n"
"\n"
"function onOpen(evt)\n"
"{    \n"
"    $(\"#dashboardTitle\").html(\"Dashboard - connected\");\n"
"}\n"
"\n"
"function onClose(evt)\n"
"{\n"
"    $(\"#dashboardTitle\").html(\"Dashboard - not connected\");\n"
"}\n"
"\n"
"function onMessage(evt)\n"
"{\n"
"    //console.log(evt.data);\n"
"\n"
"    var messageData = JSON.parse(evt.data);\n"
"\n"
"    switch(messageData.type)\n"
"    {\n"
"        case \"currentWeather\":\n"
"            updateInternetCurrent(messageData);\n"
"            break;\n"
"        case \"monitorInfo\":\n"
"            updateMonitorInfo(messageData);\n"
"            break;            \n"
"    }\n"
"}\n"
"\n"
"function onError(evt)\n"
"{\n"
"}\n"
"\n"
"function doSend(message)\n"
"{\n"
"    websocket.send(message);\n"
"}\n"
"\n"
"window.addEventListener(\"load\", init, false);\n"
""
};